const LOCAL_LOGO_MAP = {
  "AC Milan": "logos/ac_milan.png",
  "ac milan": "logos/ac_milan.png",
  "acmilan": "logos/ac_milan.png",
  "AEK Athens": "logos/aek_athens.png",
  "aek athens": "logos/aek_athens.png",
  "aekathens": "logos/aek_athens.png",
  "AIK": "logos/aik.png",
  "aik": "logos/aik.png",
  "AS Roma": "logos/as_roma.png",
  "as roma": "logos/as_roma.png",
  "asroma": "logos/as_roma.png",
  "AZ Alkmaar": "logos/az_alkmaar.png",
  "az alkmaar": "logos/az_alkmaar.png",
  "azalkmaar": "logos/az_alkmaar.png",
  "Aberdeen": "logos/aberdeen_fc.png",
  "aberdeen": "logos/aberdeen_fc.png",
  "Adana Demirspor": "logos/adanademirspor.png",
  "adana demirspor": "logos/adanademirspor.png",
  "adanademirspor": "logos/adanademirspor.png",
  "Ajax": "logos/ajax.png",
  "ajax": "logos/ajax.png",
  "Al-Taawoun": "logos/altaysk.png",
  "al-taawoun": "logos/altaysk.png",
  "altaawoun": "logos/altaysk.png",
  "Alanyaspor": "logos/alanyaspor.png",
  "alanyaspor": "logos/alanyaspor.png",
  "Alaves": "logos/alaves.png",
  "alaves": "logos/alaves.png",
  "Anderlecht": "logos/rsc_anderlecht.png",
  "anderlecht": "logos/rsc_anderlecht.png",
  "Angers": "logos/angers_sco.png",
  "angers": "logos/angers_sco.png",
  "Antalyaspor": "logos/antalyaspor.png",
  "antalyaspor": "logos/antalyaspor.png",
  "Antwerp": "logos/royalantwerp.png",
  "antwerp": "logos/royalantwerp.png",
  "Aris": "logos/aelarisa.png",
  "aris": "logos/aelarisa.png",
  "Arouca": "logos/arouca.png",
  "arouca": "logos/arouca.png",
  "Arsenal": "logos/arsenal.png",
  "arsenal": "logos/arsenal.png",
  "Asteras Tripolis": "logos/asterastripolis.png",
  "asteras tripolis": "logos/asterastripolis.png",
  "asterastripolis": "logos/asterastripolis.png",
  "Aston Villa": "logos/aston_villa.png",
  "aston villa": "logos/aston_villa.png",
  "astonvilla": "logos/aston_villa.png",
  "Atalanta": "logos/atalanta_bc.png",
  "atalanta": "logos/atalanta_bc.png",
  "Athletic Bilbao": "logos/athletic_bilbao.png",
  "athletic bilbao": "logos/athletic_bilbao.png",
  "athleticbilbao": "logos/athletic_bilbao.png",
  "Atletico Madrid": "logos/atleticodemadrid.png",
  "atletico madrid": "logos/atleticodemadrid.png",
  "atleticomadrid": "logos/atleticodemadrid.png",
  "Atletico-MG": "logos/atleticodemadrid.png",
  "atletico-mg": "logos/atleticodemadrid.png",
  "atleticomg": "logos/atleticodemadrid.png",
  "Atromitos": "logos/atromitosathen.png",
  "atromitos": "logos/atromitosathen.png",
  "Augsburg": "logos/fc_augsburg.png",
  "augsburg": "logos/fc_augsburg.png",
  "Austria Vienna": "logos/austria_vienna.png",
  "austria vienna": "logos/austria_vienna.png",
  "austriavienna": "logos/austria_vienna.png",
  "Auxerre": "logos/aj_auxerre.png",
  "auxerre": "logos/aj_auxerre.png",
  "BK Hacken": "logos/bkhacken.png",
  "bk hacken": "logos/bkhacken.png",
  "bkhacken": "logos/bkhacken.png",
  "Barcelona": "logos/barcelona.png",
  "barcelona": "logos/barcelona.png",
  "Bayer Leverkusen": "logos/bayer_04_leverkusen.png",
  "bayer leverkusen": "logos/bayer_04_leverkusen.png",
  "bayerleverkusen": "logos/bayer_04_leverkusen.png",
  "Bayern Munich": "logos/bayern_munich.png",
  "bayern munich": "logos/bayern_munich.png",
  "bayernmunich": "logos/bayern_munich.png",
  "Başakşehir": "logos/basaksehir.png",
  "başakşehir": "logos/basaksehir.png",
  "basaksehir": "logos/basaksehir.png",
  "Benfica": "logos/benfica.png",
  "benfica": "logos/benfica.png",
  "Beşiktaş": "logos/besiktas.png",
  "beşiktaş": "logos/besiktas.png",
  "besiktas": "logos/besiktas.png",
  "Boavista": "logos/boavistafc.png",
  "boavista": "logos/boavistafc.png",
  "Bodrum FK": "logos/bodrumfk.png",
  "bodrum fk": "logos/bodrumfk.png",
  "bodrumfk": "logos/bodrumfk.png",
  "Bologna": "logos/bologna_fc_1909.png",
  "bologna": "logos/bologna_fc_1909.png",
  "Borussia Dortmund": "logos/borussia_dortmund.png",
  "borussia dortmund": "logos/borussia_dortmund.png",
  "borussiadortmund": "logos/borussia_dortmund.png",
  "Borussia M'gladbach": "logos/borussia_dortmund.png",
  "borussia m'gladbach": "logos/borussia_dortmund.png",
  "borussiamgladbach": "logos/borussia_dortmund.png",
  "Bournemouth": "logos/afc_bournemouth.png",
  "bournemouth": "logos/afc_bournemouth.png",
  "Braga": "logos/sc_braga.png",
  "braga": "logos/sc_braga.png",
  "Brann": "logos/sk_brann.png",
  "brann": "logos/sk_brann.png",
  "Brentford": "logos/brentford_fc.png",
  "brentford": "logos/brentford_fc.png",
  "Brest": "logos/stade_brestois_29.png",
  "brest": "logos/stade_brestois_29.png",
  "Brighton": "logos/brighton.png",
  "brighton": "logos/brighton.png",
  "Brondby IF": "logos/brondbyif.png",
  "brondby if": "logos/brondbyif.png",
  "brondbyif": "logos/brondbyif.png",
  "Burnley": "logos/burnley.png",
  "burnley": "logos/burnley.png",
  "Cagliari": "logos/cagliari_calcio.png",
  "cagliari": "logos/cagliari_calcio.png",
  "Casa Pia": "logos/casa_pia_ac.png",
  "casa pia": "logos/casa_pia_ac.png",
  "casapia": "logos/casa_pia_ac.png",
  "Celta Vigo": "logos/celta_de_vigo.png",
  "celta vigo": "logos/celta_de_vigo.png",
  "celtavigo": "logos/celta_de_vigo.png",
  "Celtic": "logos/celta_de_vigo.png",
  "celtic": "logos/celta_de_vigo.png",
  "Cercle Brugge": "logos/cercle_brugge.png",
  "cercle brugge": "logos/cercle_brugge.png",
  "cerclebrugge": "logos/cercle_brugge.png",
  "Charleroi": "logos/rcharleroisc.png",
  "charleroi": "logos/rcharleroisc.png",
  "Chelsea": "logos/chelsea.png",
  "chelsea": "logos/chelsea.png",
  "Club Brugge": "logos/clubbrugge.png",
  "club brugge": "logos/clubbrugge.png",
  "clubbrugge": "logos/clubbrugge.png",
  "Como": "logos/como_1907.png",
  "como": "logos/como_1907.png",
  "Coventry": "logos/coventry_city.png",
  "coventry": "logos/coventry_city.png",
  "Cracovia": "logos/cracovia.png",
  "cracovia": "logos/cracovia.png",
  "Crystal Palace": "logos/crystal_palace.png",
  "crystal palace": "logos/crystal_palace.png",
  "crystalpalace": "logos/crystal_palace.png",
  "Djurgarden": "logos/djurg_rdens_if.png",
  "djurgarden": "logos/djurg_rdens_if.png",
  "Dundee": "logos/dundee_fc.png",
  "dundee": "logos/dundee_fc.png",
  "Dundee Utd": "logos/dundee_fc.png",
  "dundee utd": "logos/dundee_fc.png",
  "dundeeutd": "logos/dundee_fc.png",
  "Eintracht Frankfurt": "logos/eintracht_frankfurt.png",
  "eintracht frankfurt": "logos/eintracht_frankfurt.png",
  "eintrachtfrankfurt": "logos/eintracht_frankfurt.png",
  "Elfsborg": "logos/if_elfsborg.png",
  "elfsborg": "logos/if_elfsborg.png",
  "Empoli": "logos/fcempoli.png",
  "empoli": "logos/fcempoli.png",
  "Espanyol": "logos/espanyol.png",
  "espanyol": "logos/espanyol.png",
  "Estoril": "logos/estorilpraia.png",
  "estoril": "logos/estorilpraia.png",
  "Everton": "logos/everton_fc.png",
  "everton": "logos/everton_fc.png",
  "Eyüpspor": "logos/eyupspor.png",
  "eyüpspor": "logos/eyupspor.png",
  "eyupspor": "logos/eyupspor.png",
  "FC Basel": "logos/fcbasel.png",
  "fc basel": "logos/fcbasel.png",
  "fcbasel": "logos/fcbasel.png",
  "FC Copenhagen": "logos/fc_copenhagen.png",
  "fc copenhagen": "logos/fc_copenhagen.png",
  "fccopenhagen": "logos/fc_copenhagen.png",
  "FC Luzern": "logos/fc_luzern.png",
  "fc luzern": "logos/fc_luzern.png",
  "fcluzern": "logos/fc_luzern.png",
  "FC Midtjylland": "logos/fc_midtjylland.png",
  "fc midtjylland": "logos/fc_midtjylland.png",
  "fcmidtjylland": "logos/fc_midtjylland.png",
  "FC Nordsjaelland": "logos/fc_nordsjaelland.png",
  "fc nordsjaelland": "logos/fc_nordsjaelland.png",
  "fcnordsjaelland": "logos/fc_nordsjaelland.png",
  "FC St. Gallen": "logos/fcstgallen.png",
  "fc st. gallen": "logos/fcstgallen.png",
  "fcstgallen": "logos/fcstgallen.png",
  "FC Winterthur": "logos/fcwinterthur.png",
  "fc winterthur": "logos/fcwinterthur.png",
  "fcwinterthur": "logos/fcwinterthur.png",
  "FC Zurich": "logos/fczurich.png",
  "fc zurich": "logos/fczurich.png",
  "fczurich": "logos/fczurich.png",
  "Farense": "logos/scfarense.png",
  "farense": "logos/scfarense.png",
  "Fenerbahçe": "logos/fenerbahce.png",
  "fenerbahçe": "logos/fenerbahce.png",
  "fenerbahce": "logos/fenerbahce.png",
  "Feyenoord": "logos/feyenoord.png",
  "feyenoord": "logos/feyenoord.png",
  "Fiorentina": "logos/acf_fiorentina.png",
  "fiorentina": "logos/acf_fiorentina.png",
  "Fortaleza": "logos/fortuna_sittard.png",
  "fortaleza": "logos/fortuna_sittard.png",
  "Fortuna Sittard": "logos/fortuna_sittard.png",
  "fortuna sittard": "logos/fortuna_sittard.png",
  "fortunasittard": "logos/fortuna_sittard.png",
  "Fredrikstad": "logos/fredrikstad_fk.png",
  "fredrikstad": "logos/fredrikstad_fk.png",
  "Freiburg": "logos/sc_freiburg.png",
  "freiburg": "logos/sc_freiburg.png",
  "Fulham": "logos/fulham_fc.png",
  "fulham": "logos/fulham_fc.png",
  "GAIS": "logos/gais.png",
  "gais": "logos/gais.png",
  "Galatasaray": "logos/galatasaray.png",
  "galatasaray": "logos/galatasaray.png",
  "Gaziantep FK": "logos/gaziantep_fk.png",
  "gaziantep fk": "logos/gaziantep_fk.png",
  "gaziantepfk": "logos/gaziantep_fk.png",
  "Genk": "logos/krc_genk.png",
  "genk": "logos/krc_genk.png",
  "Genoa": "logos/genoa_cfc.png",
  "genoa": "logos/genoa_cfc.png",
  "Gent": "logos/kaa_gent.png",
  "gent": "logos/kaa_gent.png",
  "Getafe": "logos/getafe_cf.png",
  "getafe": "logos/getafe_cf.png",
  "Gil Vicente": "logos/gil_vicente_fc.png",
  "gil vicente": "logos/gil_vicente_fc.png",
  "gilvicente": "logos/gil_vicente_fc.png",
  "Girona": "logos/gironafc.png",
  "girona": "logos/gironafc.png",
  "Go Ahead Eagles": "logos/go_ahead_eagles.png",
  "go ahead eagles": "logos/go_ahead_eagles.png",
  "goaheadeagles": "logos/go_ahead_eagles.png",
  "Gornik Zabrze": "logos/gornikzabrze.png",
  "gornik zabrze": "logos/gornikzabrze.png",
  "gornikzabrze": "logos/gornikzabrze.png",
  "Grasshoppers": "logos/grasshopper_club_zurich.png",
  "grasshoppers": "logos/grasshopper_club_zurich.png",
  "Groningen": "logos/fc_groningen.png",
  "groningen": "logos/fc_groningen.png",
  "Göztepe": "logos/goztepe.png",
  "göztepe": "logos/goztepe.png",
  "goztepe": "logos/goztepe.png",
  "Hammarby": "logos/hammarby_if.png",
  "hammarby": "logos/hammarby_if.png",
  "Hatayspor": "logos/hatayspor.png",
  "hatayspor": "logos/hatayspor.png",
  "Hearts": "logos/heartofmidl.png",
  "hearts": "logos/heartofmidl.png",
  "Heerenveen": "logos/heerenveen.png",
  "heerenveen": "logos/heerenveen.png",
  "Heidenheim": "logos/1fcheidenheim1846.png",
  "heidenheim": "logos/1fcheidenheim1846.png",
  "Heracles": "logos/heraclesalmelo.png",
  "heracles": "logos/heraclesalmelo.png",
  "Hibernian": "logos/hibernian_fc.png",
  "hibernian": "logos/hibernian_fc.png",
  "Holstein Kiel": "logos/holsteinkiel.png",
  "holstein kiel": "logos/holsteinkiel.png",
  "holsteinkiel": "logos/holsteinkiel.png",
  "Hull": "logos/hull_city.png",
  "hull": "logos/hull_city.png",
  "IFK Goteborg": "logos/ifkgoteborg.png",
  "ifk goteborg": "logos/ifkgoteborg.png",
  "ifkgoteborg": "logos/ifkgoteborg.png",
  "IFK Norrkoping": "logos/ifknorrkoping.png",
  "ifk norrkoping": "logos/ifknorrkoping.png",
  "ifknorrkoping": "logos/ifknorrkoping.png",
  "Inter": "logos/fcwinterthur.png",
  "inter": "logos/fcwinterthur.png",
  "Inter Miami": "logos/inter_milan.png",
  "inter miami": "logos/inter_milan.png",
  "intermiami": "logos/inter_milan.png",
  "Internacional": "logos/inter_milan.png",
  "internacional": "logos/inter_milan.png",
  "Ipswich": "logos/ipswich_town.png",
  "ipswich": "logos/ipswich_town.png",
  "Jagiellonia Bialystok": "logos/jagiellonia_bialystok.png",
  "jagiellonia bialystok": "logos/jagiellonia_bialystok.png",
  "jagielloniabialystok": "logos/jagiellonia_bialystok.png",
  "Juventude": "logos/juventus.png",
  "juventude": "logos/juventus.png",
  "Juventus": "logos/juventus.png",
  "juventus": "logos/juventus.png",
  "KFUM Oslo": "logos/kfumkamerateneoslo.png",
  "kfum oslo": "logos/kfumkamerateneoslo.png",
  "kfumoslo": "logos/kfumkamerateneoslo.png",
  "KV Kortrijk": "logos/kv_kortrijk.png",
  "kv kortrijk": "logos/kv_kortrijk.png",
  "kvkortrijk": "logos/kv_kortrijk.png",
  "Kasımpaşa": "logos/kasimpasa.png",
  "kasımpaşa": "logos/kasimpasa.png",
  "kasimpasa": "logos/kasimpasa.png",
  "Kayserispor": "logos/kayserispor.png",
  "kayserispor": "logos/kayserispor.png",
  "Kilmarnock": "logos/kilmarnock_fc.png",
  "kilmarnock": "logos/kilmarnock_fc.png",
  "Konyaspor": "logos/konyaspor.png",
  "konyaspor": "logos/konyaspor.png",
  "LASK": "logos/lask.png",
  "lask": "logos/lask.png",
  "Lamia": "logos/paslamia1964.png",
  "lamia": "logos/paslamia1964.png",
  "Las Palmas": "logos/udlaspalmas.png",
  "las palmas": "logos/udlaspalmas.png",
  "laspalmas": "logos/udlaspalmas.png",
  "Lazio": "logos/lazio.png",
  "lazio": "logos/lazio.png",
  "Le Havre": "logos/le_havre_ac.png",
  "le havre": "logos/le_havre_ac.png",
  "lehavre": "logos/le_havre_ac.png",
  "Lecce": "logos/us_lecce.png",
  "lecce": "logos/us_lecce.png",
  "Lech Poznan": "logos/lech_poznan.png",
  "lech poznan": "logos/lech_poznan.png",
  "lechpoznan": "logos/lech_poznan.png",
  "Leeds": "logos/leeds_united.png",
  "leeds": "logos/leeds_united.png",
  "Leganes": "logos/cdleganes.png",
  "leganes": "logos/cdleganes.png",
  "Legia Warsaw": "logos/legia_warszawa.png",
  "legia warsaw": "logos/legia_warszawa.png",
  "legiawarsaw": "logos/legia_warszawa.png",
  "Leicester": "logos/leicestercity.png",
  "leicester": "logos/leicestercity.png",
  "Lens": "logos/rc_lens.png",
  "lens": "logos/rc_lens.png",
  "Lille": "logos/lillestr_m_sk.png",
  "lille": "logos/lillestr_m_sk.png",
  "Lillestrom": "logos/lillestr_m_sk.png",
  "lillestrom": "logos/lillestr_m_sk.png",
  "Liverpool": "logos/liverpool_fc.png",
  "liverpool": "logos/liverpool_fc.png",
  "Lugano": "logos/fc_lugano.png",
  "lugano": "logos/fc_lugano.png",
  "Lyngby BK": "logos/lyngbybk.png",
  "lyngby bk": "logos/lyngbybk.png",
  "lyngbybk": "logos/lyngbybk.png",
  "Lyon": "logos/olympique_lyon.png",
  "lyon": "logos/olympique_lyon.png",
  "Mainz": "logos/1_fsv_mainz_05.png",
  "mainz": "logos/1_fsv_mainz_05.png",
  "Mallorca": "logos/rcdmallorca.png",
  "mallorca": "logos/rcdmallorca.png",
  "Malmo FF": "logos/malmoff.png",
  "malmo ff": "logos/malmoff.png",
  "malmoff": "logos/malmoff.png",
  "Manchester City": "logos/manchester_city.png",
  "manchester city": "logos/manchester_city.png",
  "manchestercity": "logos/manchester_city.png",
  "Manchester United": "logos/manchester_united.png",
  "manchester united": "logos/manchester_united.png",
  "manchesterunited": "logos/manchester_united.png",
  "Marseille": "logos/marseille.png",
  "marseille": "logos/marseille.png",
  "Mechelen": "logos/kv_mechelen.png",
  "mechelen": "logos/kv_mechelen.png",
  "Mjallby AIF": "logos/mjallbyaif.png",
  "mjallby aif": "logos/mjallbyaif.png",
  "mjallbyaif": "logos/mjallbyaif.png",
  "Molde": "logos/molde_fk.png",
  "molde": "logos/molde_fk.png",
  "Monaco": "logos/as_monaco.png",
  "monaco": "logos/as_monaco.png",
  "Montpellier": "logos/montpellier.png",
  "montpellier": "logos/montpellier.png",
  "Monza": "logos/ac_monza.png",
  "monza": "logos/ac_monza.png",
  "Moreirense": "logos/moreirense_fc.png",
  "moreirense": "logos/moreirense_fc.png",
  "Motherwell": "logos/motherwell_fc.png",
  "motherwell": "logos/motherwell_fc.png",
  "NEC Nijmegen": "logos/nec_nijmegen.png",
  "nec nijmegen": "logos/nec_nijmegen.png",
  "necnijmegen": "logos/nec_nijmegen.png",
  "Nantes": "logos/fcnantes.png",
  "nantes": "logos/fcnantes.png",
  "Napoli": "logos/ssc_napoli.png",
  "napoli": "logos/ssc_napoli.png",
  "Newcastle": "logos/newcastle_united.png",
  "newcastle": "logos/newcastle_united.png",
  "Nice": "logos/ogc_nice.png",
  "nice": "logos/ogc_nice.png",
  "Norwich": "logos/norwich.png",
  "norwich": "logos/norwich.png",
  "Nottingham Forest": "logos/nottingham_forest.png",
  "nottingham forest": "logos/nottingham_forest.png",
  "nottinghamforest": "logos/nottingham_forest.png",
  "OFI Crete": "logos/ofi_crete.png",
  "ofi crete": "logos/ofi_crete.png",
  "oficrete": "logos/ofi_crete.png",
  "OH Leuven": "logos/ohleuven.png",
  "oh leuven": "logos/ohleuven.png",
  "ohleuven": "logos/ohleuven.png",
  "Olympiacos": "logos/olympiacos.png",
  "olympiacos": "logos/olympiacos.png",
  "Osasuna": "logos/ca_osasuna.png",
  "osasuna": "logos/ca_osasuna.png",
  "PAOK": "logos/paok_thessaloniki.png",
  "paok": "logos/paok_thessaloniki.png",
  "PEC Zwolle": "logos/pec_zwolle.png",
  "pec zwolle": "logos/pec_zwolle.png",
  "peczwolle": "logos/pec_zwolle.png",
  "PSV Eindhoven": "logos/psv_eindhoven.png",
  "psv eindhoven": "logos/psv_eindhoven.png",
  "psveindhoven": "logos/psv_eindhoven.png",
  "Panathinaikos": "logos/panathinaikos.png",
  "panathinaikos": "logos/panathinaikos.png",
  "Panserraikos": "logos/panserraikos.png",
  "panserraikos": "logos/panserraikos.png",
  "Paris SG": "logos/parissg.png",
  "paris sg": "logos/parissg.png",
  "parissg": "logos/parissg.png",
  "Parma": "logos/parma_calcio_1913.png",
  "parma": "logos/parma_calcio_1913.png",
  "Piast Gliwice": "logos/piast_gliwice.png",
  "piast gliwice": "logos/piast_gliwice.png",
  "piastgliwice": "logos/piast_gliwice.png",
  "Pogon Szczecin": "logos/pogon_szczecin.png",
  "pogon szczecin": "logos/pogon_szczecin.png",
  "pogonszczecin": "logos/pogon_szczecin.png",
  "Porto": "logos/fc_porto.png",
  "porto": "logos/fc_porto.png",
  "RB Leipzig": "logos/rb_leipzig.png",
  "rb leipzig": "logos/rb_leipzig.png",
  "rbleipzig": "logos/rb_leipzig.png",
  "Racing Club": "logos/racing_santander.png",
  "racing club": "logos/racing_santander.png",
  "racingclub": "logos/racing_santander.png",
  "Rakow Czestochowa": "logos/rakowczestochowa.png",
  "rakow czestochowa": "logos/rakowczestochowa.png",
  "rakowczestochowa": "logos/rakowczestochowa.png",
  "Randers FC": "logos/randers_fc.png",
  "randers fc": "logos/randers_fc.png",
  "randersfc": "logos/randers_fc.png",
  "Rangers": "logos/rangers.png",
  "rangers": "logos/rangers.png",
  "Rapid Vienna": "logos/rapid_vienna.png",
  "rapid vienna": "logos/rapid_vienna.png",
  "rapidvienna": "logos/rapid_vienna.png",
  "Rayo Vallecano": "logos/rayo_vallecano.png",
  "rayo vallecano": "logos/rayo_vallecano.png",
  "rayovallecano": "logos/rayo_vallecano.png",
  "Real Betis": "logos/realbetisbalompie.png",
  "real betis": "logos/realbetisbalompie.png",
  "realbetis": "logos/realbetisbalompie.png",
  "Real Madrid": "logos/real_madrid.png",
  "real madrid": "logos/real_madrid.png",
  "realmadrid": "logos/real_madrid.png",
  "Real Salt Lake": "logos/realbetisbalompie.png",
  "real salt lake": "logos/realbetisbalompie.png",
  "realsaltlake": "logos/realbetisbalompie.png",
  "Real Sociedad": "logos/real_sociedad.png",
  "real sociedad": "logos/real_sociedad.png",
  "realsociedad": "logos/real_sociedad.png",
  "Red Bull Bragantino": "logos/red_bull_salzburg.png",
  "red bull bragantino": "logos/red_bull_salzburg.png",
  "redbullbragantino": "logos/red_bull_salzburg.png",
  "Red Bull Salzburg": "logos/red_bull_salzburg.png",
  "red bull salzburg": "logos/red_bull_salzburg.png",
  "redbullsalzburg": "logos/red_bull_salzburg.png",
  "Reims": "logos/stadereims.png",
  "reims": "logos/stadereims.png",
  "Rio Ave": "logos/rio_ave_fc.png",
  "rio ave": "logos/rio_ave_fc.png",
  "rioave": "logos/rio_ave_fc.png",
  "Rizespor": "logos/caykur_rizespor.png",
  "rizespor": "logos/caykur_rizespor.png",
  "Rosenborg": "logos/rosenborg_bk.png",
  "rosenborg": "logos/rosenborg_bk.png",
  "Ross County": "logos/rosscountyfc.png",
  "ross county": "logos/rosscountyfc.png",
  "rosscounty": "logos/rosscountyfc.png",
  "SCR Altach": "logos/scr_altach.png",
  "scr altach": "logos/scr_altach.png",
  "scraltach": "logos/scr_altach.png",
  "SK Austria Klagenfurt": "logos/skaustriaklagenfurt.png",
  "sk austria klagenfurt": "logos/skaustriaklagenfurt.png",
  "skaustriaklagenfurt": "logos/skaustriaklagenfurt.png",
  "Samsunspor": "logos/samsunspor.png",
  "samsunspor": "logos/samsunspor.png",
  "Santa Clara": "logos/santaclara.png",
  "santa clara": "logos/santaclara.png",
  "santaclara": "logos/santaclara.png",
  "Sarpsborg 08": "logos/sarpsborg_08_ff.png",
  "sarpsborg 08": "logos/sarpsborg_08_ff.png",
  "sarpsborg08": "logos/sarpsborg_08_ff.png",
  "Servette": "logos/servette_fc.png",
  "servette": "logos/servette_fc.png",
  "Sevilla": "logos/sevilla_fc.png",
  "sevilla": "logos/sevilla_fc.png",
  "Sheffield Utd": "logos/sheffieldunited.png",
  "sheffield utd": "logos/sheffieldunited.png",
  "sheffieldutd": "logos/sheffieldunited.png",
  "Silkeborg IF": "logos/silkeborg_if.png",
  "silkeborg if": "logos/silkeborg_if.png",
  "silkeborgif": "logos/silkeborg_if.png",
  "Sint-Truiden": "logos/sinttruidensevv.png",
  "sint-truiden": "logos/sinttruidensevv.png",
  "sinttruiden": "logos/sinttruidensevv.png",
  "Sivasspor": "logos/sivasspor.png",
  "sivasspor": "logos/sivasspor.png",
  "Slask Wroclaw": "logos/slask_wroclaw.png",
  "slask wroclaw": "logos/slask_wroclaw.png",
  "slaskwroclaw": "logos/slask_wroclaw.png",
  "Southampton": "logos/southampton.png",
  "southampton": "logos/southampton.png",
  "Sparta Rotterdam": "logos/sparta_rotterdam.png",
  "sparta rotterdam": "logos/sparta_rotterdam.png",
  "spartarotterdam": "logos/sparta_rotterdam.png",
  "Sporting CP": "logos/sporting_cp.png",
  "sporting cp": "logos/sporting_cp.png",
  "sportingcp": "logos/sporting_cp.png",
  "St. Johnstone": "logos/stjohnstone.png",
  "st. johnstone": "logos/stjohnstone.png",
  "stjohnstone": "logos/stjohnstone.png",
  "St. Mirren": "logos/stmirren.png",
  "st. mirren": "logos/stmirren.png",
  "stmirren": "logos/stmirren.png",
  "St. Pauli": "logos/fcstpauli.png",
  "st. pauli": "logos/fcstpauli.png",
  "stpauli": "logos/fcstpauli.png",
  "Standard Liege": "logos/standardliege.png",
  "standard liege": "logos/standardliege.png",
  "standardliege": "logos/standardliege.png",
  "Strasbourg": "logos/rc_strasbourg_alsace.png",
  "strasbourg": "logos/rc_strasbourg_alsace.png",
  "Sturm Graz": "logos/sk_sturm_graz.png",
  "sturm graz": "logos/sk_sturm_graz.png",
  "sturmgraz": "logos/sk_sturm_graz.png",
  "Sunderland": "logos/sunderland_afc.png",
  "sunderland": "logos/sunderland_afc.png",
  "TSV Hartberg": "logos/tsv_hartberg.png",
  "tsv hartberg": "logos/tsv_hartberg.png",
  "tsvhartberg": "logos/tsv_hartberg.png",
  "Torino": "logos/torino_fc.png",
  "torino": "logos/torino_fc.png",
  "Tottenham": "logos/tottenham_hotspur.png",
  "tottenham": "logos/tottenham_hotspur.png",
  "Toulouse": "logos/fc_toulouse.png",
  "toulouse": "logos/fc_toulouse.png",
  "Trabzonspor": "logos/trabzonspor.png",
  "trabzonspor": "logos/trabzonspor.png",
  "Tromso": "logos/troms__il.png",
  "tromso": "logos/troms__il.png",
  "Twente": "logos/fc_twente_enschede.png",
  "twente": "logos/fc_twente_enschede.png",
  "Udinese": "logos/udinese_calcio.png",
  "udinese": "logos/udinese_calcio.png",
  "Union Berlin": "logos/1_fc_union_berlin.png",
  "union berlin": "logos/1_fc_union_berlin.png",
  "unionberlin": "logos/1_fc_union_berlin.png",
  "Union St. Gilloise": "logos/union_saint-gilloise.png",
  "union st. gilloise": "logos/union_saint-gilloise.png",
  "unionstgilloise": "logos/union_saint-gilloise.png",
  "Utrecht": "logos/fc_utrecht.png",
  "utrecht": "logos/fc_utrecht.png",
  "Valencia": "logos/valencia.png",
  "valencia": "logos/valencia.png",
  "Valladolid": "logos/realvalladolidcf.png",
  "valladolid": "logos/realvalladolidcf.png",
  "Vejle Boldklub": "logos/vejleboldklub.png",
  "vejle boldklub": "logos/vejleboldklub.png",
  "vejleboldklub": "logos/vejleboldklub.png",
  "Venezia": "logos/venezia.png",
  "venezia": "logos/venezia.png",
  "Verona": "logos/hellasverona.png",
  "verona": "logos/hellasverona.png",
  "VfB Stuttgart": "logos/vfb_stuttgart.png",
  "vfb stuttgart": "logos/vfb_stuttgart.png",
  "vfbstuttgart": "logos/vfb_stuttgart.png",
  "VfL Bochum": "logos/vflbochum.png",
  "vfl bochum": "logos/vflbochum.png",
  "vflbochum": "logos/vflbochum.png",
  "Viborg FF": "logos/viborg_ff.png",
  "viborg ff": "logos/viborg_ff.png",
  "viborgff": "logos/viborg_ff.png",
  "Viking": "logos/viking_fk.png",
  "viking": "logos/viking_fk.png",
  "Villarreal": "logos/villarreal_cf.png",
  "villarreal": "logos/villarreal_cf.png",
  "Vitoria Guimaraes": "logos/vitoriaguimaressc.png",
  "vitoria guimaraes": "logos/vitoriaguimaressc.png",
  "vitoriaguimaraes": "logos/vitoriaguimaressc.png",
  "Volos": "logos/volos_nfc.png",
  "volos": "logos/volos_nfc.png",
  "Watford": "logos/watfordfc.png",
  "watford": "logos/watfordfc.png",
  "Werder Bremen": "logos/sv_werder_bremen.png",
  "werder bremen": "logos/sv_werder_bremen.png",
  "werderbremen": "logos/sv_werder_bremen.png",
  "West Brom": "logos/westham.png",
  "west brom": "logos/westham.png",
  "westbrom": "logos/westham.png",
  "West Ham": "logos/westham.png",
  "west ham": "logos/westham.png",
  "westham": "logos/westham.png",
  "Westerlo": "logos/kvc_westerlo.png",
  "westerlo": "logos/kvc_westerlo.png",
  "Widzew Lodz": "logos/widzew_lodz.png",
  "widzew lodz": "logos/widzew_lodz.png",
  "widzewlodz": "logos/widzew_lodz.png",
  "Willem II": "logos/willemii.png",
  "willem ii": "logos/willemii.png",
  "willemii": "logos/willemii.png",
  "Wolfsberger AC": "logos/wolfsberger_ac.png",
  "wolfsberger ac": "logos/wolfsberger_ac.png",
  "wolfsbergerac": "logos/wolfsberger_ac.png",
  "Wolfsburg": "logos/vflwolfsburg.png",
  "wolfsburg": "logos/vflwolfsburg.png",
  "Wolves": "logos/wolverhamptonwanderers.png",
  "wolves": "logos/wolverhamptonwanderers.png",
  "Young Boys": "logos/bsc_young_boys.png",
  "young boys": "logos/bsc_young_boys.png",
  "youngboys": "logos/bsc_young_boys.png",
  "Yverdon": "logos/yverdonsportfc.png",
  "yverdon": "logos/yverdonsportfc.png",
  "AGF Aarhus": "logos/agfaarhus.png",
  "agf aarhus": "logos/agfaarhus.png",
  "agfaarhus": "logos/agfaarhus.png",
  "Al-Ahli": "logos/alahli.png",
  "al-ahli": "logos/alahli.png",
  "alahli": "logos/alahli.png",
  "Al-Ettifaq": "logos/alettifaq.png",
  "al-ettifaq": "logos/alettifaq.png",
  "alettifaq": "logos/alettifaq.png",
  "Al-Fateh": "logos/alfateh.png",
  "al-fateh": "logos/alfateh.png",
  "alfateh": "logos/alfateh.png",
  "Al-Fayha": "logos/alfayha.png",
  "al-fayha": "logos/alfayha.png",
  "alfayha": "logos/alfayha.png",
  "Al-Hilal": "logos/alhilal.png",
  "al-hilal": "logos/alhilal.png",
  "alhilal": "logos/alhilal.png",
  "Al-Ittihad": "logos/alittihad.png",
  "al-ittihad": "logos/alittihad.png",
  "alittihad": "logos/alittihad.png",
  "Al-Khaleej": "logos/alkhaleej.png",
  "al-khaleej": "logos/alkhaleej.png",
  "alkhaleej": "logos/alkhaleej.png",
  "Al-Nassr": "logos/alnassr.png",
  "al-nassr": "logos/alnassr.png",
  "alnassr": "logos/alnassr.png",
  "Al-Shabab": "logos/alshabab.png",
  "al-shabab": "logos/alshabab.png",
  "alshabab": "logos/alshabab.png",
  "Argentinos Juniors": "logos/argentinosjuniors.png",
  "argentinos juniors": "logos/argentinosjuniors.png",
  "argentinosjuniors": "logos/argentinosjuniors.png",
  "Bahia": "logos/bahia.png",
  "bahia": "logos/bahia.png",
  "Blackburn": "logos/blackburn.png",
  "blackburn": "logos/blackburn.png",
  "Boca Juniors": "logos/bocajuniors.png",
  "boca juniors": "logos/bocajuniors.png",
  "bocajuniors": "logos/bocajuniors.png",
  "Bodo/Glimt": "logos/bodoglimt.png",
  "bodo/glimt": "logos/bodoglimt.png",
  "bodoglimt": "logos/bodoglimt.png",
  "Botafogo": "logos/botafogo.png",
  "botafogo": "logos/botafogo.png",
  "Bristol City": "logos/bristolcity.png",
  "bristol city": "logos/bristolcity.png",
  "bristolcity": "logos/bristolcity.png",
  "Colorado Rapids": "logos/coloradorapids.png",
  "colorado rapids": "logos/coloradorapids.png",
  "coloradorapids": "logos/coloradorapids.png",
  "Columbus Crew": "logos/columbuscrew.png",
  "columbus crew": "logos/columbuscrew.png",
  "columbuscrew": "logos/columbuscrew.png",
  "Corinthians": "logos/corinthians.png",
  "corinthians": "logos/corinthians.png",
  "Cruzeiro": "logos/cruzeiro.png",
  "cruzeiro": "logos/cruzeiro.png",
  "Defensa y Justicia": "logos/defensayjusticia.png",
  "defensa y justicia": "logos/defensayjusticia.png",
  "defensayjusticia": "logos/defensayjusticia.png",
  "Estudiantes": "logos/estudiantes.png",
  "estudiantes": "logos/estudiantes.png",
  "FC Cincinnati": "logos/fccincinnati.png",
  "fc cincinnati": "logos/fccincinnati.png",
  "fccincinnati": "logos/fccincinnati.png",
  "Famalicao": "logos/famalicao.png",
  "famalicao": "logos/famalicao.png",
  "Flamengo": "logos/flamengo.png",
  "flamengo": "logos/flamengo.png",
  "Fluminense": "logos/fluminense.png",
  "fluminense": "logos/fluminense.png",
  "Godoy Cruz": "logos/godoycruz.png",
  "godoy cruz": "logos/godoycruz.png",
  "godoycruz": "logos/godoycruz.png",
  "Gremio": "logos/gremio.png",
  "gremio": "logos/gremio.png",
  "Houston Dynamo": "logos/houstondynamo.png",
  "houston dynamo": "logos/houstondynamo.png",
  "houstondynamo": "logos/houstondynamo.png",
  "Huracan": "logos/huracan.png",
  "huracan": "logos/huracan.png",
  "Independiente": "logos/independiente.png",
  "independiente": "logos/independiente.png",
  "LA Galaxy": "logos/lagalaxy.png",
  "la galaxy": "logos/lagalaxy.png",
  "lagalaxy": "logos/lagalaxy.png",
  "Lanús": "logos/lanus.png",
  "lanús": "logos/lanus.png",
  "lanus": "logos/lanus.png",
  "Los Angeles FC": "logos/losangelesfc.png",
  "los angeles fc": "logos/losangelesfc.png",
  "losangelesfc": "logos/losangelesfc.png",
  "Middlesbrough": "logos/middlesbrough.png",
  "middlesbrough": "logos/middlesbrough.png",
  "Millwall": "logos/millwall.png",
  "millwall": "logos/millwall.png",
  "New York Red Bulls": "logos/newyorkredbulls.png",
  "new york red bulls": "logos/newyorkredbulls.png",
  "newyorkredbulls": "logos/newyorkredbulls.png",
  "Palmeiras": "logos/palmeiras.png",
  "palmeiras": "logos/palmeiras.png",
  "Preston": "logos/preston.png",
  "preston": "logos/preston.png",
  "Rennes": "logos/rennes.png",
  "rennes": "logos/rennes.png",
  "River Plate": "logos/riverplate.png",
  "river plate": "logos/riverplate.png",
  "riverplate": "logos/riverplate.png",
  "Rosario Central": "logos/rosariocentral.png",
  "rosario central": "logos/rosariocentral.png",
  "rosariocentral": "logos/rosariocentral.png",
  "Saint-Etienne": "logos/saintetienne.png",
  "saint-etienne": "logos/saintetienne.png",
  "saintetienne": "logos/saintetienne.png",
  "San Lorenzo": "logos/sanlorenzo.png",
  "san lorenzo": "logos/sanlorenzo.png",
  "sanlorenzo": "logos/sanlorenzo.png",
  "Sao Paulo": "logos/saopaulo.png",
  "sao paulo": "logos/saopaulo.png",
  "saopaulo": "logos/saopaulo.png",
  "Seattle Sounders": "logos/seattlesounders.png",
  "seattle sounders": "logos/seattlesounders.png",
  "seattlesounders": "logos/seattlesounders.png",
  "Stoke": "logos/stoke.png",
  "stoke": "logos/stoke.png",
  "Swansea": "logos/swansea.png",
  "swansea": "logos/swansea.png",
  "TSG Hoffenheim": "logos/tsghoffenheim.png",
  "tsg hoffenheim": "logos/tsghoffenheim.png",
  "tsghoffenheim": "logos/tsghoffenheim.png",
  "Talleres": "logos/talleres.png",
  "talleres": "logos/talleres.png",
  "Vasco da Gama": "logos/vascodagama.png",
  "vasco da gama": "logos/vascodagama.png",
  "vascodagama": "logos/vascodagama.png",
  "Velez Sarsfield": "logos/velezsarsfield.png",
  "velez sarsfield": "logos/velezsarsfield.png",
  "velezsarsfield": "logos/velezsarsfield.png"
};
