// GOLANALIZ AI - Doğrulanmış Model Başarı Defteri
window.AI_PERFORMANCE_DATA = {
  "summary": {
    "winRate": 81.6,
    "overallWinRate": 78.1,
    "totalMatches": 500,
    "allTimeMatches": 20145,
    "wonMatches": 408,
    "lostMatches": 92,
    "lastUpdated": "13.09.2026 02:08",
    "engineVersion": "Dixon-Coles Quant Engine 5.0 (Auto-Audited)"
  },
  "categories": {
    "kart": {
      "total": 10318,
      "won": 9771,
      "label": "Sarı / Kırmızı Kart",
      "winRate": 94.7
    },
    "taraf": {
      "total": 1482,
      "won": 1101,
      "label": "Maç Sonucu & Çifte Şans",
      "winRate": 74.3
    },
    "gol": {
      "total": 5773,
      "won": 3237,
      "label": "Alt / Üst & KG",
      "winRate": 56.1
    },
    "korner": {
      "total": 2572,
      "won": 1624,
      "label": "Korner Bahisleri",
      "winRate": 63.1
    }
  },
  "recentLedger": [
    {
      "date": "18/01/2025",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Beşiktaş",
      "awayTeam": "Bodrum FK",
      "score": "2-1",
      "corners": "8-3",
      "cards": "2-2",
      "prediction": "ÇİFTE ŞANS 1-X",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.35,
      "confidence": 91,
      "reason": "Beşiktaş iç saha üstünlüğü ve form momentumu ile kaybetmemeye yakın (%91).",
      "status": "WON"
    },
    {
      "date": "05/01/2025",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Bodrum FK",
      "awayTeam": "Kayserispor",
      "score": "1-0",
      "corners": "5-3",
      "cards": "1-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (2.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "14/12/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Bodrum FK",
      "awayTeam": "Sivasspor",
      "score": "1-2",
      "corners": "5-4",
      "cards": "2-2",
      "prediction": "ÇİFTE ŞANS X-2",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.42,
      "confidence": 85,
      "reason": "Sivasspor deplasmanda güçlü form grafiği ile puan almaya aday (%85).",
      "status": "WON"
    },
    {
      "date": "09/12/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Trabzonspor",
      "awayTeam": "Bodrum FK",
      "score": "1-0",
      "corners": "7-3",
      "cards": "1-1",
      "prediction": "ÇİFTE ŞANS 1-X",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.35,
      "confidence": 91,
      "reason": "Trabzonspor iç saha üstünlüğü ve form momentumu ile kaybetmemeye yakın (%91).",
      "status": "WON"
    },
    {
      "date": "30/11/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Samsunspor",
      "awayTeam": "Bodrum FK",
      "score": "4-0",
      "corners": "6-3",
      "cards": "1-2",
      "prediction": "TOPLAM GOL 2.5 ALT",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.78,
      "confidence": 79,
      "reason": "Düşük xG toplamı (1.58) ve kontrollü savunma yapısı 2.5 Alt lehine.",
      "status": "LOST"
    },
    {
      "date": "23/11/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Bodrum FK",
      "awayTeam": "Galatasaray",
      "score": "0-1",
      "corners": "3-8",
      "cards": "2-1",
      "prediction": "ÇİFTE ŞANS X-2",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.42,
      "confidence": 94,
      "reason": "Galatasaray deplasmanda güçlü form grafiği ile puan almaya aday (%94).",
      "status": "WON"
    },
    {
      "date": "09/11/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Erzurumspor",
      "awayTeam": "Bodrum FK",
      "score": "3-2",
      "corners": "5-6",
      "cards": "2-3",
      "prediction": "TOPLAM GOL 2.5 ALT",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.78,
      "confidence": 94,
      "reason": "Düşük xG toplamı (0.86) ve kontrollü savunma yapısı 2.5 Alt lehine.",
      "status": "LOST"
    },
    {
      "date": "03/11/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Bodrum FK",
      "awayTeam": "Alanyaspor",
      "score": "0-0",
      "corners": "4-5",
      "cards": "2-2",
      "prediction": "TOPLAM GOL 2.5 ALT",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.78,
      "confidence": 95,
      "reason": "Düşük xG toplamı (0.84) ve kontrollü savunma yapısı 2.5 Alt lehine.",
      "status": "WON"
    },
    {
      "date": "27/10/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Fenerbahçe",
      "awayTeam": "Bodrum FK",
      "score": "2-0",
      "corners": "9-2",
      "cards": "1-2",
      "prediction": "TOPLAM GOL 2.5 ALT",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.78,
      "confidence": 87,
      "reason": "Düşük xG toplamı (1.26) ve kontrollü savunma yapısı 2.5 Alt lehine.",
      "status": "WON"
    },
    {
      "date": "21/10/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Bodrum FK",
      "awayTeam": "Rizespor",
      "score": "0-1",
      "corners": "6-3",
      "cards": "1-2",
      "prediction": "TOPLAM GOL 2.5 ALT",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.78,
      "confidence": 80,
      "reason": "Düşük xG toplamı (1.52) ve kontrollü savunma yapısı 2.5 Alt lehine.",
      "status": "WON"
    },
    {
      "date": "05/10/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Kasımpaşa",
      "awayTeam": "Bodrum FK",
      "score": "0-0",
      "corners": "5-4",
      "cards": "2-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (1.8) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "20/09/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Hatayspor",
      "awayTeam": "Bodrum FK",
      "score": "0-1",
      "corners": "4-4",
      "cards": "2-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (1.8) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "14/09/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Bodrum FK",
      "awayTeam": "Başakşehir",
      "score": "0-1",
      "corners": "3-6",
      "cards": "2-1",
      "prediction": "ÇİFTE ŞANS X-2",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.42,
      "confidence": 91,
      "reason": "Başakşehir deplasmanda güçlü form grafiği ile puan almaya aday (%91).",
      "status": "WON"
    },
    {
      "date": "31/08/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Göztepe",
      "awayTeam": "Bodrum FK",
      "score": "2-0",
      "corners": "5-3",
      "cards": "3-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 66,
      "reason": "Dixon-Coles xG toplamı 3.55 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "24/08/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Bodrum FK",
      "awayTeam": "Konyaspor",
      "score": "3-1",
      "corners": "4-5",
      "cards": "2-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (2.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "19/08/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Eyüpspor",
      "awayTeam": "Bodrum FK",
      "score": "4-1",
      "corners": "6-4",
      "cards": "1-2",
      "prediction": "ÇİFTE ŞANS 1-X",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.35,
      "confidence": 87,
      "reason": "Eyüpspor iç saha üstünlüğü ve form momentumu ile kaybetmemeye yakın (%87).",
      "status": "WON"
    },
    {
      "date": "12/08/2024",
      "time": "20:00",
      "league": "Türkiye Süper Lig",
      "country": "TR",
      "homeTeam": "Bodrum FK",
      "awayTeam": "Gaziantep FK",
      "score": "0-1",
      "corners": "5-3",
      "cards": "2-3",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (2.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "06/09/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "St Johnstone",
      "awayTeam": "Hibernian",
      "score": "2-1",
      "corners": "2-7",
      "cards": "1-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (1.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "06/09/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Hearts",
      "awayTeam": "Dundee",
      "score": "2-1",
      "corners": "14-2",
      "cards": "2-3",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 60,
      "reason": "Dixon-Coles xG toplamı 6.08 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "05/09/2026",
      "time": "20:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "St Mirren",
      "awayTeam": "Celtic",
      "score": "1-2",
      "corners": "6-10",
      "cards": "4-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 66,
      "reason": "Dixon-Coles xG toplamı 4.11 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "05/09/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Rangers",
      "awayTeam": "Motherwell",
      "score": "1-0",
      "corners": "7-5",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 71,
      "reason": "Dixon-Coles xG toplamı 6.95 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "05/09/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Dundee United",
      "awayTeam": "Falkirk",
      "score": "1-1",
      "corners": "14-5",
      "cards": "3-2",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 57,
      "reason": "Dixon-Coles xG toplamı 3.01 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "05/09/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Aberdeen",
      "awayTeam": "Kilmarnock",
      "score": "0-0",
      "corners": "6-7",
      "cards": "5-3",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 59,
      "reason": "Dixon-Coles xG toplamı 4.91 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "03/09/2026",
      "time": "19:45",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Hibernian",
      "awayTeam": "Hearts",
      "score": "1-3",
      "corners": "7-8",
      "cards": "3-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 73,
      "reason": "Dixon-Coles xG toplamı 4.02 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "02/09/2026",
      "time": "20:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Falkirk",
      "awayTeam": "Rangers",
      "score": "1-2",
      "corners": "5-6",
      "cards": "2-1",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (2.4) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "02/09/2026",
      "time": "19:45",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Motherwell",
      "awayTeam": "Dundee United",
      "score": "3-0",
      "corners": "9-3",
      "cards": "1-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 72,
      "reason": "Dixon-Coles xG toplamı 4.08 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "02/09/2026",
      "time": "19:45",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Kilmarnock",
      "awayTeam": "St Mirren",
      "score": "0-1",
      "corners": "7-3",
      "cards": "2-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "02/09/2026",
      "time": "19:45",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Dundee",
      "awayTeam": "St Johnstone",
      "score": "1-1",
      "corners": "2-5",
      "cards": "0-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "02/09/2026",
      "time": "19:45",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Celtic",
      "awayTeam": "Aberdeen",
      "score": "3-0",
      "corners": "15-5",
      "cards": "1-1",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "06/09/2026",
      "time": "19:30",
      "league": "Yunanistan Super League",
      "country": "GRE",
      "homeTeam": "Panathinaikos",
      "awayTeam": "PAOK",
      "score": "3-1",
      "corners": "5-2",
      "cards": "3-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 71,
      "reason": "Dixon-Coles xG toplamı 4.88 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "06/09/2026",
      "time": "18:00",
      "league": "Yunanistan Super League",
      "country": "GRE",
      "homeTeam": "Levadeiakos",
      "awayTeam": "Panetolikos",
      "score": "0-2",
      "corners": "8-2",
      "cards": "0-3",
      "prediction": "ÇİFTE ŞANS X-2",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.42,
      "confidence": 93,
      "reason": "Panetolikos deplasmanda güçlü form grafiği ile puan almaya aday (%93).",
      "status": "WON"
    },
    {
      "date": "06/09/2026",
      "time": "17:30",
      "league": "Yunanistan Super League",
      "country": "GRE",
      "homeTeam": "OFI Crete",
      "awayTeam": "Kifisia",
      "score": "2-0",
      "corners": "1-9",
      "cards": "2-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "05/09/2026",
      "time": "19:00",
      "league": "Yunanistan Super League",
      "country": "GRE",
      "homeTeam": "AEK",
      "awayTeam": "Aris",
      "score": "5-0",
      "corners": "2-2",
      "cards": "2-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "05/09/2026",
      "time": "17:00",
      "league": "Yunanistan Super League",
      "country": "GRE",
      "homeTeam": "Volos NFC",
      "awayTeam": "Olympiakos",
      "score": "1-1",
      "corners": "0-9",
      "cards": "6-1",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "06/09/2026",
      "time": "18:15",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Beveren",
      "awayTeam": "Oud-Heverlee Leuven",
      "score": "3-0",
      "corners": "7-5",
      "cards": "2-2",
      "prediction": "ÇİFTE ŞANS X-2",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.42,
      "confidence": 93,
      "reason": "Oud-Heverlee Leuven deplasmanda güçlü form grafiği ile puan almaya aday (%93).",
      "status": "LOST"
    },
    {
      "date": "06/09/2026",
      "time": "17:30",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Anderlecht",
      "awayTeam": "Genk",
      "score": "0-0",
      "corners": "4-2",
      "cards": "2-1",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.4) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "06/09/2026",
      "time": "15:00",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Kortrijk",
      "awayTeam": "Waregem",
      "score": "0-2",
      "corners": "6-6",
      "cards": "2-5",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.8) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "06/09/2026",
      "time": "12:30",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Cercle Brugge",
      "awayTeam": "Gent",
      "score": "0-3",
      "corners": "8-0",
      "cards": "1-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.2) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "05/09/2026",
      "time": "19:45",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Standard",
      "awayTeam": "Antwerp",
      "score": "1-0",
      "corners": "13-4",
      "cards": "1-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "05/09/2026",
      "time": "19:45",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "St Truiden",
      "awayTeam": "RAAL La Louviere",
      "score": "4-0",
      "corners": "12-5",
      "cards": "1-2",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 68,
      "reason": "Dixon-Coles xG toplamı 3.63 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "05/09/2026",
      "time": "17:15",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Mechelen",
      "awayTeam": "Westerlo",
      "score": "0-4",
      "corners": "5-6",
      "cards": "3-2",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 75,
      "reason": "Dixon-Coles xG toplamı 4.94 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "05/09/2026",
      "time": "15:00",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Charleroi",
      "awayTeam": "St. Gilloise",
      "score": "2-3",
      "corners": "5-6",
      "cards": "1-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.4) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "04/09/2026",
      "time": "19:45",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Lommel SK",
      "awayTeam": "Club Brugge",
      "score": "0-1",
      "corners": "2-9",
      "cards": "1-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (1.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "03/09/2026",
      "time": "19:30",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Gent",
      "awayTeam": "Oud-Heverlee Leuven",
      "score": "1-0",
      "corners": "10-1",
      "cards": "1-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "03/09/2026",
      "time": "19:30",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Anderlecht",
      "awayTeam": "Kortrijk",
      "score": "1-0",
      "corners": "7-2",
      "cards": "2-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "02/09/2026",
      "time": "19:30",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "St Truiden",
      "awayTeam": "St. Gilloise",
      "score": "0-3",
      "corners": "3-1",
      "cards": "3-2",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "07/09/2026",
      "time": "20:15",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Estoril",
      "awayTeam": "Arouca",
      "score": "0-0",
      "corners": "8-2",
      "cards": "4-1",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "LOST"
    },
    {
      "date": "06/09/2026",
      "time": "20:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Gil Vicente",
      "awayTeam": "Academico Viseu",
      "score": "0-1",
      "corners": "7-1",
      "cards": "0-2",
      "prediction": "ÇİFTE ŞANS 1-X",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.35,
      "confidence": 89,
      "reason": "Gil Vicente iç saha üstünlüğü ve form momentumu ile kaybetmemeye yakın (%89).",
      "status": "LOST"
    },
    {
      "date": "06/09/2026",
      "time": "18:00",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Guimaraes",
      "awayTeam": "Casa Pia",
      "score": "0-0",
      "corners": "17-4",
      "cards": "2-2",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 77,
      "reason": "Dixon-Coles xG toplamı 4.49 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "06/09/2026",
      "time": "15:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Santa Clara",
      "awayTeam": "Rio Ave",
      "score": "4-0",
      "corners": "8-2",
      "cards": "1-1",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (1.6) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    }
  ]
};
