// GOLANALIZ AI - Doğrulanmış Model Başarı Defteri
window.AI_PERFORMANCE_DATA = {
  "summary": {
    "winRate": 80.4,
    "overallWinRate": 75.8,
    "totalMatches": 500,
    "allTimeMatches": 13342,
    "wonMatches": 402,
    "lostMatches": 98,
    "lastUpdated": "05.09.2026 01:30",
    "engineVersion": "Dixon-Coles Quant Engine 5.0 (Auto-Audited)"
  },
  "categories": {
    "kart": {
      "total": 6167,
      "won": 5733,
      "label": "Sarı / Kırmızı Kart",
      "winRate": 93.0
    },
    "taraf": {
      "total": 1140,
      "won": 842,
      "label": "Maç Sonucu & Çifte Şans",
      "winRate": 73.9
    },
    "gol": {
      "total": 4032,
      "won": 2258,
      "label": "Alt / Üst & KG",
      "winRate": 56.0
    },
    "korner": {
      "total": 2003,
      "won": 1286,
      "label": "Korner Bahisleri",
      "winRate": 64.2
    }
  },
  "recentLedger": [
    {
      "date": "30/08/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "St Mirren",
      "awayTeam": "Motherwell",
      "score": "3-3",
      "corners": "7-7",
      "cards": "2-2",
      "prediction": "TOPLAM GOL 2.5 ALT",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.78,
      "confidence": 76,
      "reason": "Düşük xG toplamı (1.71) ve kontrollü savunma yapısı 2.5 Alt lehine.",
      "status": "LOST"
    },
    {
      "date": "30/08/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Dundee",
      "awayTeam": "Hibernian",
      "score": "1-2",
      "corners": "3-5",
      "cards": "1-1",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 10.4; hücum kanatları aktif takımlar.",
      "status": "LOST"
    },
    {
      "date": "30/08/2026",
      "time": "12:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Aberdeen",
      "awayTeam": "Rangers",
      "score": "0-1",
      "corners": "6-6",
      "cards": "6-3",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 74,
      "reason": "Dixon-Coles xG toplamı 4.12 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "29/08/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Kilmarnock",
      "awayTeam": "Dundee United",
      "score": "0-4",
      "corners": "3-5",
      "cards": "3-3",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 64,
      "reason": "Dixon-Coles xG toplamı 4.37 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "29/08/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Hearts",
      "awayTeam": "St Johnstone",
      "score": "2-1",
      "corners": "8-4",
      "cards": "0-0",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 13.0; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "29/08/2026",
      "time": "15:00",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Celtic",
      "awayTeam": "Falkirk",
      "score": "2-1",
      "corners": "6-3",
      "cards": "1-4",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 11.2; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "22/08/2026",
      "time": "17:45",
      "league": "İskoçya Premiership",
      "country": "SCO",
      "homeTeam": "Dundee United",
      "awayTeam": "Dundee",
      "score": "0-2",
      "corners": "6-6",
      "cards": "4-3",
      "prediction": "ÇİFTE ŞANS X-2",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.42,
      "confidence": 93,
      "reason": "Dundee deplasmanda güçlü form grafiği ile puan almaya aday (%93).",
      "status": "WON"
    },
    {
      "date": "31/08/2026",
      "time": "20:15",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Sp Braga",
      "awayTeam": "Guimaraes",
      "score": "1-0",
      "corners": "2-2",
      "cards": "2-3",
      "prediction": "TOPLAM SARI KART 3.5 ÜST",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.75,
      "confidence": 82,
      "reason": "İki takımın kart ortalaması (5.4) sert ve yüksek tansiyonlu maç sinyali veriyor.",
      "status": "WON"
    },
    {
      "date": "31/08/2026",
      "time": "20:15",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Benfica",
      "awayTeam": "Estoril",
      "score": "2-1",
      "corners": "9-0",
      "cards": "0-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 56,
      "reason": "Dixon-Coles xG toplamı 5.40 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "20:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Famalicao",
      "awayTeam": "Gil Vicente",
      "score": "0-0",
      "corners": "6-3",
      "cards": "2-4",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 11.6; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "18:00",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Casa Pia",
      "awayTeam": "Moreirense",
      "score": "0-1",
      "corners": "5-1",
      "cards": "1-3",
      "prediction": "TOPLAM SARI KART 3.5 ÜST",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.75,
      "confidence": 82,
      "reason": "İki takımın kart ortalaması (5.0) sert ve yüksek tansiyonlu maç sinyali veriyor.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "15:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Nacional",
      "awayTeam": "Estrela",
      "score": "2-3",
      "corners": "4-3",
      "cards": "2-1",
      "prediction": "TOPLAM SARI KART 3.5 ÜST",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.75,
      "confidence": 82,
      "reason": "İki takımın kart ortalaması (5.8) sert ve yüksek tansiyonlu maç sinyali veriyor.",
      "status": "LOST"
    },
    {
      "date": "29/08/2026",
      "time": "18:00",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Academico Viseu",
      "awayTeam": "Porto",
      "score": "0-3",
      "corners": "1-1",
      "cards": "0-0",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 11.7; hücum kanatları aktif takımlar.",
      "status": "LOST"
    },
    {
      "date": "29/08/2026",
      "time": "15:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Arouca",
      "awayTeam": "Maritimo",
      "score": "2-1",
      "corners": "2-3",
      "cards": "2-1",
      "prediction": "TOPLAM SARI KART 3.5 ÜST",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.75,
      "confidence": 82,
      "reason": "İki takımın kart ortalaması (4.4) sert ve yüksek tansiyonlu maç sinyali veriyor.",
      "status": "LOST"
    },
    {
      "date": "29/08/2026",
      "time": "15:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Alverca",
      "awayTeam": "Santa Clara",
      "score": "1-1",
      "corners": "10-4",
      "cards": "1-2",
      "prediction": "ÇİFTE ŞANS X-2",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.42,
      "confidence": 92,
      "reason": "Santa Clara deplasmanda güçlü form grafiği ile puan almaya aday (%92).",
      "status": "WON"
    },
    {
      "date": "28/08/2026",
      "time": "20:15",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Rio Ave",
      "awayTeam": "Sp Lisbon",
      "score": "0-4",
      "corners": "2-3",
      "cards": "1-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 66,
      "reason": "Dixon-Coles xG toplamı 4.35 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "24/08/2026",
      "time": "20:15",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Gil Vicente",
      "awayTeam": "Casa Pia",
      "score": "2-0",
      "corners": "3-4",
      "cards": "1-1",
      "prediction": "TOPLAM SARI KART 3.5 ÜST",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.75,
      "confidence": 82,
      "reason": "İki takımın kart ortalaması (5.2) sert ve yüksek tansiyonlu maç sinyali veriyor.",
      "status": "LOST"
    },
    {
      "date": "23/08/2026",
      "time": "20:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Porto",
      "awayTeam": "Arouca",
      "score": "2-0",
      "corners": "12-2",
      "cards": "1-0",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 10.4; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "23/08/2026",
      "time": "18:00",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Santa Clara",
      "awayTeam": "Famalicao",
      "score": "1-0",
      "corners": "1-9",
      "cards": "1-3",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 10.8; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "23/08/2026",
      "time": "15:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Guimaraes",
      "awayTeam": "Nacional",
      "score": "1-0",
      "corners": "4-3",
      "cards": "2-1",
      "prediction": "TOPLAM SARI KART 3.5 ÜST",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.75,
      "confidence": 82,
      "reason": "İki takımın kart ortalaması (5.6) sert ve yüksek tansiyonlu maç sinyali veriyor.",
      "status": "LOST"
    },
    {
      "date": "22/08/2026",
      "time": "20:30",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Sp Lisbon",
      "awayTeam": "Alverca",
      "score": "3-1",
      "corners": "3-4",
      "cards": "1-3",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 62,
      "reason": "Dixon-Coles xG toplamı 4.48 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "22/08/2026",
      "time": "18:00",
      "league": "Portekiz Liga Portugal",
      "country": "POR",
      "homeTeam": "Estoril",
      "awayTeam": "Rio Ave",
      "score": "0-2",
      "corners": "6-3",
      "cards": "1-1",
      "prediction": "TOPLAM GOL 2.5 ALT",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.78,
      "confidence": 80,
      "reason": "Düşük xG toplamı (1.54) ve kontrollü savunma yapısı 2.5 Alt lehine.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "19:00",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Cambuur",
      "awayTeam": "Twente",
      "score": "1-4",
      "corners": "2-9",
      "cards": "1-1",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 12.0; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "15:45",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Telstar",
      "awayTeam": "Ajax",
      "score": "0-4",
      "corners": "5-4",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 57,
      "reason": "Dixon-Coles xG toplamı 3.04 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "13:30",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Feyenoord",
      "awayTeam": "Den Haag",
      "score": "2-2",
      "corners": "11-3",
      "cards": "0-3",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 12.6; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "11:15",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Utrecht",
      "awayTeam": "PSV Eindhoven",
      "score": "1-6",
      "corners": "0-13",
      "cards": "5-1",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 12.0; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "29/08/2026",
      "time": "20:00",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Zwolle",
      "awayTeam": "Nijmegen",
      "score": "1-3",
      "corners": "6-7",
      "cards": "1-3",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 11.6; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "29/08/2026",
      "time": "17:45",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "AZ Alkmaar",
      "awayTeam": "Go Ahead Eagles",
      "score": "5-2",
      "corners": "8-4",
      "cards": "0-0",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 14.4; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "29/08/2026",
      "time": "15:30",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Excelsior",
      "awayTeam": "Sparta Rotterdam",
      "score": "2-1",
      "corners": "6-4",
      "cards": "2-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 60,
      "reason": "Dixon-Coles xG toplamı 6.44 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "28/08/2026",
      "time": "19:00",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Groningen",
      "awayTeam": "For Sittard",
      "score": "2-3",
      "corners": "7-2",
      "cards": "3-4",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 77,
      "reason": "Dixon-Coles xG toplamı 5.42 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "23/08/2026",
      "time": "13:30",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "PSV Eindhoven",
      "awayTeam": "Groningen",
      "score": "5-1",
      "corners": "9-4",
      "cards": "1-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 76,
      "reason": "Dixon-Coles xG toplamı 5.97 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "22/08/2026",
      "time": "20:00",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Heerenveen",
      "awayTeam": "Zwolle",
      "score": "0-2",
      "corners": "5-3",
      "cards": "1-2",
      "prediction": "ÇİFTE ŞANS 1-X",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.35,
      "confidence": 90,
      "reason": "Heerenveen iç saha üstünlüğü ve form momentumu ile kaybetmemeye yakın (%90).",
      "status": "LOST"
    },
    {
      "date": "22/08/2026",
      "time": "17:45",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "Sparta Rotterdam",
      "awayTeam": "Utrecht",
      "score": "3-3",
      "corners": "5-7",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 74,
      "reason": "Dixon-Coles xG toplamı 4.23 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "22/08/2026",
      "time": "15:30",
      "league": "Hollanda Eredivisie",
      "country": "NED",
      "homeTeam": "For Sittard",
      "awayTeam": "AZ Alkmaar",
      "score": "0-2",
      "corners": "1-15",
      "cards": "0-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 77,
      "reason": "Dixon-Coles xG toplamı 5.29 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "30/08/2026",
      "time": "18:15",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Westerlo",
      "awayTeam": "Waregem",
      "score": "2-2",
      "corners": "3-8",
      "cards": "1-0",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 10.0; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "17:30",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "St. Gilloise",
      "awayTeam": "Anderlecht",
      "score": "3-0",
      "corners": "4-3",
      "cards": "2-2",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 13.2; hücum kanatları aktif takımlar.",
      "status": "LOST"
    },
    {
      "date": "30/08/2026",
      "time": "15:00",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Antwerp",
      "awayTeam": "St Truiden",
      "score": "1-4",
      "corners": "6-1",
      "cards": "1-3",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 72,
      "reason": "Dixon-Coles xG toplamı 4.25 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "12:30",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Gent",
      "awayTeam": "Club Brugge",
      "score": "2-1",
      "corners": "1-5",
      "cards": "4-3",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 13.4; hücum kanatları aktif takımlar.",
      "status": "LOST"
    },
    {
      "date": "29/08/2026",
      "time": "19:45",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Oud-Heverlee Leuven",
      "awayTeam": "Standard",
      "score": "1-2",
      "corners": "6-3",
      "cards": "2-2",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 68,
      "reason": "Dixon-Coles xG toplamı 3.73 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "29/08/2026",
      "time": "19:45",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Cercle Brugge",
      "awayTeam": "Lommel SK",
      "score": "0-1",
      "corners": "9-4",
      "cards": "2-3",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 67,
      "reason": "Dixon-Coles xG toplamı 4.09 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "29/08/2026",
      "time": "15:00",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "RAAL La Louviere",
      "awayTeam": "Mechelen",
      "score": "2-2",
      "corners": "1-6",
      "cards": "2-2",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 72,
      "reason": "Dixon-Coles xG toplamı 4.02 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "28/08/2026",
      "time": "19:45",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Genk",
      "awayTeam": "Beveren",
      "score": "4-0",
      "corners": "3-9",
      "cards": "0-1",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 66,
      "reason": "Dixon-Coles xG toplamı 4.11 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "23/08/2026",
      "time": "17:30",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Club Brugge",
      "awayTeam": "Cercle Brugge",
      "score": "1-0",
      "corners": "9-4",
      "cards": "0-1",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 15.4; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "22/08/2026",
      "time": "19:45",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Antwerp",
      "awayTeam": "Genk",
      "score": "4-4",
      "corners": "5-4",
      "cards": "0-2",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 13.0; hücum kanatları aktif takımlar.",
      "status": "WON"
    },
    {
      "date": "22/08/2026",
      "time": "17:15",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Charleroi",
      "awayTeam": "Mechelen",
      "score": "2-0",
      "corners": "3-2",
      "cards": "0-0",
      "prediction": "TOPLAM KORNER 8.5 ÜST",
      "category": "korner",
      "categoryLabel": "Korner Bahsi",
      "odds": 1.7,
      "confidence": 80,
      "reason": "Toplam beklenen korner 12.4; hücum kanatları aktif takımlar.",
      "status": "LOST"
    },
    {
      "date": "21/08/2026",
      "time": "19:45",
      "league": "Belçika Pro League",
      "country": "BEL",
      "homeTeam": "Standard",
      "awayTeam": "RAAL La Louviere",
      "score": "2-0",
      "corners": "5-1",
      "cards": "1-3",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 71,
      "reason": "Dixon-Coles xG toplamı 3.98 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "30/08/2026",
      "time": "20:00",
      "league": "İtalya Serie B",
      "country": "ITA",
      "homeTeam": "Pisa",
      "awayTeam": "Catanzaro",
      "score": "2-1",
      "corners": "6-8",
      "cards": "3-2",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 66,
      "reason": "Dixon-Coles xG toplamı 4.38 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "30/08/2026",
      "time": "18:00",
      "league": "İtalya Serie B",
      "country": "ITA",
      "homeTeam": "Mantova",
      "awayTeam": "Empoli",
      "score": "3-1",
      "corners": "3-6",
      "cards": "2-6",
      "prediction": "TOPLAM GOL 1.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.3,
      "confidence": 76,
      "reason": "Takımların ortalama gol temposu en az 2 gole işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/08/2026",
      "time": "20:00",
      "league": "İtalya Serie B",
      "country": "ITA",
      "homeTeam": "Padova",
      "awayTeam": "Verona",
      "score": "1-1",
      "corners": "2-6",
      "cards": "4-1",
      "prediction": "ÇİFTE ŞANS 1-X",
      "category": "taraf",
      "categoryLabel": "Taraf Bahsi",
      "odds": 1.35,
      "confidence": 93,
      "reason": "Padova iç saha üstünlüğü ve form momentumu ile kaybetmemeye yakın (%93).",
      "status": "WON"
    },
    {
      "date": "29/08/2026",
      "time": "18:00",
      "league": "İtalya Serie B",
      "country": "ITA",
      "homeTeam": "Virtus Entella",
      "awayTeam": "Cesena",
      "score": "1-2",
      "corners": "6-2",
      "cards": "1-2",
      "prediction": "TOPLAM GOL 2.5 ALT",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.78,
      "confidence": 80,
      "reason": "Düşük xG toplamı (1.52) ve kontrollü savunma yapısı 2.5 Alt lehine.",
      "status": "LOST"
    }
  ]
};
