// GOLANALIZ AI - Doğrulanmış Model Başarı Defteri
window.AI_PERFORMANCE_DATA = {
  "summary": {
    "winRate": 91.8,
    "overallWinRate": 77.9,
    "totalMatches": 500,
    "allTimeMatches": 20735,
    "wonMatches": 459,
    "lostMatches": 41,
    "lastUpdated": "10.09.2026 23:54",
    "engineVersion": "Dixon-Coles Quant Engine 5.0 (Auto-Audited)"
  },
  "categories": {
    "kart": {
      "total": 10512,
      "won": 9949,
      "label": "Sarı / Kırmızı Kart",
      "winRate": 94.6
    },
    "taraf": {
      "total": 1537,
      "won": 1144,
      "label": "Maç Sonucu & Çifte Şans",
      "winRate": 74.4
    },
    "gol": {
      "total": 5976,
      "won": 3348,
      "label": "Alt / Üst & KG",
      "winRate": 56.0
    },
    "korner": {
      "total": 2710,
      "won": 1712,
      "label": "Korner Bahisleri",
      "winRate": 63.2
    }
  },
  "recentLedger": [
    {
      "date": "02/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Atlanta Utd",
      "awayTeam": "Charlotte",
      "score": "2-3",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Vancouver Whitecaps",
      "awayTeam": "Colorado Rapids",
      "score": "2-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 75,
      "reason": "Dixon-Coles xG toplamı 4.23 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Portland Timbers",
      "awayTeam": "Houston Dynamo",
      "score": "2-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Los Angeles FC",
      "awayTeam": "FC Dallas",
      "score": "1-0",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Real Salt Lake",
      "awayTeam": "Austin FC",
      "score": "5-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 75,
      "reason": "Dixon-Coles xG toplamı 4.62 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Nashville SC",
      "awayTeam": "New England Revolution",
      "score": "1-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Minnesota United",
      "awayTeam": "Sporting Kansas City",
      "score": "3-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 72,
      "reason": "Dixon-Coles xG toplamı 4.32 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Chicago Fire",
      "awayTeam": "Los Angeles Galaxy",
      "score": "2-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Philadelphia Union",
      "awayTeam": "CF Montreal",
      "score": "2-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "New York Red Bulls",
      "awayTeam": "Orlando City",
      "score": "1-0",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 74,
      "reason": "Dixon-Coles xG toplamı 4.10 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Inter Miami",
      "awayTeam": "St. Louis City",
      "score": "3-3",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "01/06/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "DC United",
      "awayTeam": "Toronto FC",
      "score": "2-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 76,
      "reason": "Dixon-Coles xG toplamı 5.88 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "31/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "New York City",
      "awayTeam": "San Jose Earthquakes",
      "score": "5-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Los Angeles FC",
      "awayTeam": "Minnesota United",
      "score": "2-0",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 74,
      "reason": "Dixon-Coles xG toplamı 4.28 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Seattle Sounders",
      "awayTeam": "Real Salt Lake",
      "score": "1-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Los Angeles Galaxy",
      "awayTeam": "FC Dallas",
      "score": "3-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Sporting Kansas City",
      "awayTeam": "Vancouver Whitecaps",
      "score": "1-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Houston Dynamo",
      "awayTeam": "Colorado Rapids",
      "score": "3-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Chicago Fire",
      "awayTeam": "Orlando City",
      "score": "1-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Austin FC",
      "awayTeam": "Portland Timbers",
      "score": "0-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Philadelphia Union",
      "awayTeam": "Toronto FC",
      "score": "0-0",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 79,
      "reason": "Dixon-Coles xG toplamı 5.62 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "New York Red Bulls",
      "awayTeam": "Charlotte",
      "score": "3-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Inter Miami",
      "awayTeam": "Atlanta Utd",
      "score": "1-3",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "FC Cincinnati",
      "awayTeam": "Nashville SC",
      "score": "0-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "29/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "CF Montreal",
      "awayTeam": "DC United",
      "score": "4-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 75,
      "reason": "Dixon-Coles xG toplamı 4.77 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Vancouver Whitecaps",
      "awayTeam": "Inter Miami",
      "score": "1-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "San Jose Earthquakes",
      "awayTeam": "Austin FC",
      "score": "1-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Portland Timbers",
      "awayTeam": "Sporting Kansas City",
      "score": "2-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 79,
      "reason": "Dixon-Coles xG toplamı 5.20 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Los Angeles Galaxy",
      "awayTeam": "Houston Dynamo",
      "score": "2-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Colorado Rapids",
      "awayTeam": "Minnesota United",
      "score": "3-3",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 74,
      "reason": "Dixon-Coles xG toplamı 4.75 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "St. Louis City",
      "awayTeam": "Seattle Sounders",
      "score": "1-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "FC Dallas",
      "awayTeam": "Real Salt Lake",
      "score": "3-3",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Toronto FC",
      "awayTeam": "FC Cincinnati",
      "score": "3-4",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Orlando City",
      "awayTeam": "Columbus Crew",
      "score": "0-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "New England Revolution",
      "awayTeam": "New York City",
      "score": "0-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "DC United",
      "awayTeam": "Chicago Fire",
      "score": "1-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Charlotte",
      "awayTeam": "Philadelphia Union",
      "score": "0-0",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "CF Montreal",
      "awayTeam": "Nashville SC",
      "score": "0-0",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "25/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Atlanta Utd",
      "awayTeam": "Los Angeles FC",
      "score": "0-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Seattle Sounders",
      "awayTeam": "Vancouver Whitecaps",
      "score": "1-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "San Jose Earthquakes",
      "awayTeam": "Orlando City",
      "score": "0-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 78,
      "reason": "Dixon-Coles xG toplamı 4.92 ile yüksek gol beklentisi mevcut.",
      "status": "LOST"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Real Salt Lake",
      "awayTeam": "Colorado Rapids",
      "score": "5-3",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Minnesota United",
      "awayTeam": "Portland Timbers",
      "score": "2-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 73,
      "reason": "Dixon-Coles xG toplamı 5.25 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Houston Dynamo",
      "awayTeam": "FC Dallas",
      "score": "1-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Chicago Fire",
      "awayTeam": "Columbus Crew",
      "score": "1-3",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Austin FC",
      "awayTeam": "Sporting Kansas City",
      "score": "3-2",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Toronto FC",
      "awayTeam": "CF Montreal",
      "score": "5-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 71,
      "reason": "Dixon-Coles xG toplamı 4.43 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "New York City",
      "awayTeam": "New York Red Bulls",
      "score": "2-1",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 75,
      "reason": "Dixon-Coles xG toplamı 5.90 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "New England Revolution",
      "awayTeam": "Philadelphia Union",
      "score": "0-3",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM GOL 2.5 ÜST",
      "category": "gol",
      "categoryLabel": "Gol Bahsi",
      "odds": 1.82,
      "confidence": 73,
      "reason": "Dixon-Coles xG toplamı 4.20 ile yüksek gol beklentisi mevcut.",
      "status": "WON"
    },
    {
      "date": "18/05/2024",
      "time": "",
      "league": "ABD Major League Soccer",
      "country": "USA",
      "homeTeam": "Inter Miami",
      "awayTeam": "DC United",
      "score": "1-0",
      "corners": "0-0",
      "cards": "0-0",
      "prediction": "TOPLAM SARI KART 3.5 ALT",
      "category": "kart",
      "categoryLabel": "Kart Bahsi",
      "odds": 1.8,
      "confidence": 78,
      "reason": "İki takımın düşük kart istatistiği (0.0) sakin bir oyun beklentisini işaret ediyor.",
      "status": "WON"
    }
  ]
};
